### ISSUE TITLE
Nature Declaration prototype fixes

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/nature-emergency#13]
Woodland Trust has given us some feedback on the prototype – http://pages.mysociety.org/nature-emergency/ – @zarino guesses it’ll be about 2 days work, maximum. Would be nice to get done in the next few weeks, before things go quiet for us/WT over August.

**Comment by lucascumsille** [comment]
### Notes call 30/07/2024

### On main branch

- [ ] Remove question mark icon
- [ ] Remove question mark logic (Tidy up)
- [ ] On main table once a council has been opened, there is no way to close it.

### On a second branch
Few ideas:
- [ ] Removing map and using the extra space for the table.
- [ ] Consider that the "Priority 1" on the others will become a short description. So a tooltip might not be the option.

## Councils

- [ ] We could try a modal that slides from the right of the screen.
- [ ] OR every council has it's own page.

Which option will depend base on the the amount of information:

- [ ] Council Name
- [ ] Declared Emergency?
- [ ] Priority 1, 2 and 3
- [ ] How similar councils are doing
- [ ] CTA how to improve
- [ ] Potential cases studies that are relevant to that council

**Comment by zarino** [comment]
Closed by #14. Thanks @lucascumsille!
